export default [
  {
    title: 'Refined Soft Sausages',
    author: 'Towels',
    genres: 'Tools',
    rating: 70,
    id: '1',
  },
  {
    title: 'Generic Bronze Mouse',
    author: 'Sausages',
    genres: 'Industrial',
    rating: 19,
    id: '2',
  },
  {
    title: 'Fantastic Rubber Chair',
    author: 'Computer',
    genres: 'Electronics',
    rating: 82,
    id: '3',
  },
  {
    title: 'Handcrafted Frozen Sausages',
    author: 'Car',
    genres: 'Beauty',
    rating: 95,
    id: '4',
  },
  {
    title: 'Handmade Concrete Hat',
    author: 'Pants',
    genres: 'Music',
    rating: 42,
    id: '5',
  },
  {
    title: 'Awesome Soft Bike',
    author: 'Towels',
    genres: 'Home',
    rating: 4,
    id: '6',
  },
  {
    title: 'Practical Frozen Chips',
    author: 'Pants',
    genres: 'Tools',
    rating: 12,
    id: '7',
  },
  {
    title: 'Sleek Steel Table',
    author: 'Ball',
    genres: 'Toys',
    rating: 67,
    id: '8',
  },
  {
    title: 'Practical Cotton Sausages',
    author: 'Car',
    genres: 'Books',
    rating: 24,
    id: '9',
  },
  {
    title: 'Practical Fresh Computer',
    author: 'Shoes',
    genres: 'Electronics',
    rating: 46,
    id: '10',
  },
  {
    title: 'Recycled Steel Shirt',
    author: 'Towels',
    genres: 'Industrial',
    rating: 28,
    id: '11',
  },
  {
    title: 'Refined Plastic Keyboard',
    author: 'Fish',
    genres: 'Shoes',
    rating: 53,
    id: '12',
  },
  {
    title: 'Licensed Cotton Salad',
    author: 'Car',
    genres: 'Grocery',
    rating: 34,
    id: '13',
  },
  {
    title: 'Awesome Cotton Tuna',
    author: 'Pizza',
    genres: 'Industrial',
    rating: 15,
    id: '14',
  },
  {
    title: 'Rustic Frozen Shoes',
    author: 'Car',
    genres: 'Toys',
    rating: 83,
    id: '15',
  },
];
